--THIS FUNCTION WAS ADOPTED FROM THE FOLLOWING WEBSITE

--https://www.kodyaz.com/t-sql/remove-numeric-characters-in-string-using-sql.aspx


CREATE FUNCTION CLEARNUMERICCHARACTERS(@STRING NVARCHAR(MAX))
RETURNS NVARCHAR(MAX)
AS
BEGIN
 WHILE PATINDEX('%[0-9]%', @STRING) > 0
  SET @STRING = STUFF(@STRING, PATINDEX('%[0-9]%', @STRING), 1, '')
 RETURN @STRING
END
